import AsyncStorage from '@react-native-async-storage/async-storage';
import React from 'react';
import { NativeModules, Platform } from 'react-native';

export type AppLanguage = 'pt' | 'en' | 'es';

type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => Promise<void>;
  t: (key: string) => string;
};

const LANGUAGE_STORAGE_KEY = '@amaidoso/language';

export const languageOptions: { code: AppLanguage; label: string }[] = [
  { code: 'pt', label: 'Português' },
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Español' },
];

const translations: Record<AppLanguage, Record<string, string>> = {
  pt: {
    about: 'Sobre',
    'Abra o e-mail e toque no link.': 'Abra o e-mail e toque no link.',
    'Ainda não': 'Ainda não',
    'adicionado.': 'adicionado.',
    'Aplicativo de apoio ao cuidado do idoso': 'Aplicativo de apoio ao cuidado do idoso',
    'Anotacao': 'Anotação',
    'Anotação': 'Anotação',
    'Anotacoes': 'Anotações',
    'Anotações do idoso': 'Anotações do idoso',
    'As medicações são cadastradas pelo responsável. Confirme quando tomar.': 'As medicações são cadastradas pelo responsável. Confirme quando tomar.',
    'As senhas nao sao iguais.': 'As senhas nao sao iguais.',
    'BackEnd': 'BackEnd',
    'Banco de Dados': 'Banco de Dados',
    'Bem Vindo ao Amaidoso': 'Bem Vindo ao Amaidoso',
    'Bem vindo ao Amaidoso': 'Bem-vindo ao Amaidoso',
    'Cadastrar idoso': 'Cadastrar idoso',
    'Cadastrar medicação': 'Cadastrar medicação',
    'CADASTRAR MEDICAÇÃO': 'CADASTRAR MEDICAÇÃO',
    'Campos obrigatórios': 'Campos obrigatórios',
    cancel: 'Cancelar',
    'Cancelar': 'Cancelar',
    'Confirme o novo e-mail': 'Confirme o novo e-mail',
    'Confirme seu e-mail': 'Confirme seu e-mail',
    'Confirmada': 'Confirmada',
    'Confirmar Medicacoes': 'Confirmar Medicações',
    'Confirmar Alteração': 'Confirmar Alteração',
    'Confirmar alterações': 'Confirmar alterações',
    'Confirmar senha': 'Confirmar senha',
    'Continuar': 'Continuar',
    configuration: 'Configurações',
    'Configurações': 'Configurações',
    'Criando...': 'Criando...',
    'Criar Conta': 'Criar Conta',
    'Criar lembrete': 'Criar lembrete',
    'Cria uma agora': 'Crie uma agora',
    'Crie Agora': 'Crie Agora',
    'Crie uma senha para o novo acesso': 'Crie uma senha para o novo acesso',
    'CPF e senha definem o login e não são alterados por aqui.': 'CPF e senha definem o login e não são alterados por aqui.',
    'CPF inválido': 'CPF inválido',
    'Cuidados do idoso': 'Cuidados do idoso',
    'Data': 'Data',
    'Data de Nascimento': 'Data de Nascimento',
    'Data de nascimento': 'Data de nascimento',
    'Definir': 'Definir',
    'Definir Data e Hora': 'Definir Data e Hora',
    'Descrição': 'Descrição',
    'Documentação': 'Documentação',
    'Digite um e-mail valido.': 'Digite um e-mail valido.',
    'Digite um email valido.': 'Digite um e-mail valido.',
    'Digite uma data valida.': 'Digite uma data valida.',
    'Digite sua senha atual': 'Digite sua senha atual',
    'Digite os 11 numeros do CPF.': 'Digite os 11 números do CPF.',
    'Depois': 'Depois',
    'Dose do medicamento': 'Dose do medicamento',
    'Demorou demais': 'Demorou demais',
    editProfile: 'Editar Perfil',
    'Editar': 'Editar',
    'Editar foto': 'Editar foto',
    'Editar idoso': 'Editar idoso',
    'Editar Perfil': 'Editar Perfil',
    email: 'E-mail',
    'Email': 'E-mail',
    'E-mail de acesso': 'E-mail de acesso',
    'Email inválido': 'Email inválido',
    'Em breve': 'Em breve',
    'Entendi': 'Entendi',
    'Enviamos um link para': 'Enviamos um link para',
    'Entrando...': 'Entrando...',
    'Entrar': 'Entrar',
    'Entre Agora': 'Entre Agora',
    'Entre agora': 'Entre agora',
    'Erro': 'Erro',
    'Erro no cadastro': 'Erro no cadastro',
    'Erro no login': 'Erro no login',
    'Escolher foto': 'Escolher foto',
    'Escolha a frequencia.': 'Escolha a frequencia.',
    'Escreva algo primeiro.': 'Escreva algo primeiro.',
    'Escreva aqui...': 'Escreva aqui...',
    'FrontEnd': 'FrontEnd',
    'FrontEnd e BackEnd': 'FrontEnd e BackEnd',
    'Frequência': 'Frequência',
    'Frequência obrigatória': 'Frequência obrigatória',
    'Fechar': 'Fechar',
    help: 'Ajuda',
    home: 'Home',
    'Home': 'Home',
    'Idioma': 'Idioma',
    'Idoso cadastrado.': 'Idoso cadastrado.',
    'Idoso não encontrado': 'Idoso não encontrado',
    'Idosos cadastrados': 'Idosos cadastrados',
    'Ir para login': 'Ir para login',
    'Ir agora': 'Ir agora',
    'Lembretes': 'Lembretes',
    'Limpar': 'Limpar',
    'Login feito': 'Login feito',
    'Marcar como visto': 'Marcar como visto',
    'Medicações': 'Medicações',
    'Medicações e confirmações': 'Medicações e confirmações',
    'Membros e contribuidores': 'Membros e contribuidores',
    'Minhas anotações': 'Minhas anotações',
    'Nascimento': 'Nascimento',
    'Nenhum Idoso cadastrado!': 'Nenhum Idoso cadastrado!',
    'Nenhum lembrete por enquanto.': 'Nenhum lembrete por enquanto.',
    'Nenhuma anotação ainda.': 'Nenhuma anotação ainda.',
    'Nenhuma anotação feita pelo idoso.': 'Nenhuma anotação feita pelo idoso.',
    'Nenhuma medicação cadastrada.': 'Nenhuma medicação cadastrada.',
    'Nome': 'Nome',
    'Nome Completo': 'Nome Completo',
    'Nome completo': 'Nome completo',
    'Nome de Usuário': 'Nome de Usuário',
    'Novo': 'Novo',
    'Novo remedio': 'Novo remédio',
    'Novo link enviado.': 'Novo link enviado.',
    'Nova anotação': 'Nova anotação',
    'Nova senha (min. 6 caracteres)': 'Nova senha (min. 6 caracteres)',
    'Não': 'Não',
    'Nao, obrigado': 'Não, obrigado',
    'Não possui uma conta?': 'Não possui uma conta?',
    'Ok': 'Ok',
    'Ola': 'Ola',
    'Olá': 'Olá',
    'O idoso vai entrar com CPF e senha.': 'O idoso vai entrar com CPF e senha.',
    'O idoso vai entrar no app usando este CPF e senha.': 'O idoso vai entrar no app usando este CPF e senha.',
    'Os lembretes são criados pelo seu responsável.': 'Os lembretes são criados pelo seu responsável.',
    'Parece que essa e a sua primeira vez aqui, deseja realizar o tutorial?': 'Parece que essa é a sua primeira vez aqui, deseja realizar o tutorial?',
    'Pendente': 'Pendente',
    'Perfil atualizado.': 'Perfil atualizado.',
    'Pode continuar.': 'Pode continuar.',
    'Possui uma conta?': 'Possui uma conta?',
    'Por favor entre na sua conta para': 'Por favor entre na sua conta para',
    'Preencha os campos com suas': 'Preencha os campos com suas',
    'Preencha CPF e senha.': 'Preencha CPF e senha.',
    'Preencha e-mail e senha.': 'Preencha e-mail e senha.',
    'Preencha medicamento e dose.': 'Preencha medicamento e dose.',
    'Preencha titulo e horario.': 'Preencha titulo e horario.',
    'Preencha todos os campos.': 'Preencha todos os campos.',
    'Permissão necessária': 'Permissão necessária',
    'Permita acessar suas fotos.': 'Permita acessar suas fotos.',
    'Projeto de TCC': 'Projeto de TCC',
    'Recuperar senha': 'Recuperar senha',
    'Reenviar link': 'Reenviar link',
    'Reenviar link em': 'Reenviar link em',
    'Reenviando...': 'Reenviando...',
    'remedios adicionados.': 'remédios adicionados.',
    'Remover foto': 'Remover foto',
    'Salvar': 'Salvar',
    'Salvar anotação': 'Salvar anotação',
    'Salvar lembrete': 'Salvar lembrete',
    'Salvando...': 'Salvando...',
    'Selecione um idoso.': 'Selecione um idoso.',
    'Senha': 'Senha',
    'Senha (mín. 6 caracteres)': 'Senha (mín. 6 caracteres)',
    'Senha atual para alterar e-mail': 'Senha atual para alterar e-mail',
    'Sem nome': 'Sem nome',
    'Sim': 'Sim',
    'Sou Idoso': 'Sou Idoso',
    'Sou Responsavel': 'Sou Responsavel',
    'Tomei': 'Tomei',
    'Título': 'Título',
    'Tudo certo': 'Tudo certo',
    'Tente de novo.': 'Tente de novo.',
    'Esta e a tela inicial onde aparecera as proximas tarefas': 'Esta é a tela inicial onde aparecerão as próximas tarefas',
    'Acima esta suas informacoes, para ver e analisa-las, clique no seu icone de perfil': 'Acima estão suas informações. Para vê-las e analisá-las, toque no seu ícone de perfil',
    'Abaixo esta a barra de navegacao, onde voce pode alterar entre as abas: Home e Configuracoes': 'Abaixo está a barra de navegação, onde você pode alternar entre as abas: Home e Configurações',
    'Toque em um idoso para abrir os cuidados': 'Toque em um idoso para abrir os cuidados',
    'Uso contínuo?': 'Uso contínuo?',
    'Use pelo menos 6 caracteres.': 'Use pelo menos 6 caracteres.',
    'Voltar': 'Voltar',
    'continuar usando nosso app': 'continuar usando nosso app',
    'informações': 'informações',
    'Avancar': 'Avançar',
    'Aqui voce altera sua foto.': 'Aqui você altera sua foto.',
    'ou': 'ou',
    language: 'Idioma',
    languageDescription: 'Escolha o idioma do aplicativo.',
    languageTitle: 'Selecionar idioma',
    logout: 'Sair',
    logoutQuestion: 'Deseja sair da conta?',
    logoutText: 'Voce voltara ao inicio.',
    notifications: 'Notificações',
    panel: 'Painel',
    responsible: 'Responsável',
    senior: 'Idoso',
    settings: 'DEFINIÇÕES',
  },
  en: {
    about: 'About',
    'Abra o e-mail e toque no link.': 'Open the email and tap the link.',
    'Ainda não': 'Not yet',
    'adicionado.': 'added.',
    'Aplicativo de apoio ao cuidado do idoso': 'App supporting senior care',
    'Anotacao': 'Note',
    'Anotação': 'Note',
    'Anotacoes': 'Notes',
    'Anotações do idoso': 'Senior notes',
    'As medicações são cadastradas pelo responsável. Confirme quando tomar.': 'Medications are added by the caregiver. Confirm when you take them.',
    'As senhas nao sao iguais.': 'The passwords do not match.',
    'BackEnd': 'BackEnd',
    'Banco de Dados': 'Database',
    'Bem Vindo ao Amaidoso': 'Welcome to Amaidoso',
    'Bem vindo ao Amaidoso': 'Welcome to Amaidoso',
    'Cadastrar idoso': 'Add senior',
    'Cadastrar medicação': 'Add medication',
    'CADASTRAR MEDICAÇÃO': 'ADD MEDICATION',
    'Campos obrigatórios': 'Required fields',
    cancel: 'Cancel',
    'Cancelar': 'Cancel',
    'Confirme o novo e-mail': 'Confirm the new email',
    'Confirme seu e-mail': 'Confirm your email',
    'Confirmada': 'Confirmed',
    'Confirmar Medicacoes': 'Confirm Medications',
    'Confirmar Alteração': 'Confirm Change',
    'Confirmar alterações': 'Confirm changes',
    'Confirmar senha': 'Confirm password',
    'Continuar': 'Continue',
    configuration: 'Settings',
    'Configurações': 'Settings',
    'Criando...': 'Creating...',
    'Criar Conta': 'Create Account',
    'Criar lembrete': 'Create reminder',
    'Cria uma agora': 'Create one now',
    'Crie Agora': 'Create Account',
    'Crie uma senha para o novo acesso': 'Create a password for the new access',
    'CPF e senha definem o login e não são alterados por aqui.': 'CPF and password define the login and cannot be changed here.',
    'CPF inválido': 'Invalid CPF',
    'Cuidados do idoso': 'Senior care',
    'Data': 'Date',
    'Data de Nascimento': 'Birth Date',
    'Data de nascimento': 'Birth date',
    'Definir': 'Set',
    'Definir Data e Hora': 'Set Date and Time',
    'Descrição': 'Description',
    'Documentação': 'Documentation',
    'Digite um e-mail valido.': 'Enter a valid email.',
    'Digite um email valido.': 'Enter a valid email.',
    'Digite uma data valida.': 'Enter a valid date.',
    'Digite sua senha atual': 'Enter your current password',
    'Digite os 11 numeros do CPF.': 'Enter the 11 CPF digits.',
    'Depois': 'Later',
    'Dose do medicamento': 'Medication dose',
    'Demorou demais': 'Taking too long',
    editProfile: 'Edit Profile',
    'Editar': 'Edit',
    'Editar foto': 'Edit photo',
    'Editar idoso': 'Edit senior',
    'Editar Perfil': 'Edit Profile',
    email: 'Email',
    'Email': 'Email',
    'E-mail de acesso': 'Access email',
    'Email inválido': 'Invalid email',
    'Em breve': 'Soon',
    'Entendi': 'Got it',
    'Enviamos um link para': 'We sent a link to',
    'Entrando...': 'Signing in...',
    'Entrar': 'Sign in',
    'Entre Agora': 'Sign In',
    'Entre agora': 'Sign in now',
    'Erro': 'Error',
    'Erro no cadastro': 'Sign-up error',
    'Erro no login': 'Login error',
    'Escolher foto': 'Choose photo',
    'Escolha a frequencia.': 'Choose the frequency.',
    'Escreva algo primeiro.': 'Write something first.',
    'Escreva aqui...': 'Write here...',
    'FrontEnd': 'FrontEnd',
    'FrontEnd e BackEnd': 'FrontEnd and BackEnd',
    'Frequência': 'Frequency',
    'Frequência obrigatória': 'Frequency required',
    'Fechar': 'Close',
    help: 'Help',
    home: 'Home',
    'Home': 'Home',
    'Idioma': 'Language',
    'Idoso cadastrado.': 'Senior added.',
    'Idoso não encontrado': 'Senior not found',
    'Idosos cadastrados': 'Registered seniors',
    'Ir para login': 'Go to login',
    'Ir agora': 'Go now',
    'Lembretes': 'Reminders',
    'Limpar': 'Clear',
    'Login feito': 'Login successful',
    'Marcar como visto': 'Mark as seen',
    'Medicações': 'Medications',
    'Medicações e confirmações': 'Medications and confirmations',
    'Membros e contribuidores': 'Members and contributors',
    'Minhas anotações': 'My notes',
    'Nascimento': 'Birth date',
    'Nenhum Idoso cadastrado!': 'No senior registered!',
    'Nenhum lembrete por enquanto.': 'No reminders for now.',
    'Nenhuma anotação ainda.': 'No notes yet.',
    'Nenhuma anotação feita pelo idoso.': 'No notes from the senior.',
    'Nenhuma medicação cadastrada.': 'No medication registered.',
    'Nome': 'Name',
    'Nome Completo': 'Full Name',
    'Nome completo': 'Full name',
    'Nome de Usuário': 'Username',
    'Novo': 'New',
    'Novo remedio': 'New medication',
    'Novo link enviado.': 'New link sent.',
    'Nova anotação': 'New note',
    'Nova senha (min. 6 caracteres)': 'New password (min. 6 characters)',
    'Não': 'No',
    'Nao, obrigado': 'No, thanks',
    'Não possui uma conta?': 'Do not have an account?',
    'Ok': 'OK',
    'Ola': 'Hello',
    'Olá': 'Hello',
    'O idoso vai entrar com CPF e senha.': 'The senior will sign in with CPF and password.',
    'O idoso vai entrar no app usando este CPF e senha.': 'The senior will sign in to the app using this CPF and password.',
    'Os lembretes são criados pelo seu responsável.': 'Reminders are created by your caregiver.',
    'Parece que essa e a sua primeira vez aqui, deseja realizar o tutorial?': 'It looks like this is your first time here. Would you like to take the tutorial?',
    'Pendente': 'Pending',
    'Perfil atualizado.': 'Profile updated.',
    'Pode continuar.': 'You can continue.',
    'Possui uma conta?': 'Already have an account?',
    'Por favor entre na sua conta para': 'Please sign in to your account to',
    'Preencha os campos com suas': 'Fill in the fields with your',
    'Preencha CPF e senha.': 'Fill in CPF and password.',
    'Preencha e-mail e senha.': 'Fill in email and password.',
    'Preencha medicamento e dose.': 'Fill in medication and dose.',
    'Preencha titulo e horario.': 'Fill in title and time.',
    'Preencha todos os campos.': 'Fill in all fields.',
    'Permissão necessária': 'Permission required',
    'Permita acessar suas fotos.': 'Allow access to your photos.',
    'Projeto de TCC': 'Capstone project',
    'Recuperar senha': 'Recover password',
    'Reenviar link': 'Resend link',
    'Reenviar link em': 'Resend link in',
    'Reenviando...': 'Resending...',
    'remedios adicionados.': 'medications added.',
    'Remover foto': 'Remove photo',
    'Salvar': 'Save',
    'Salvar anotação': 'Save note',
    'Salvar lembrete': 'Save reminder',
    'Salvando...': 'Saving...',
    'Selecione um idoso.': 'Select a senior.',
    'Senha': 'Password',
    'Senha (mín. 6 caracteres)': 'Password (min. 6 characters)',
    'Senha atual para alterar e-mail': 'Current password to change email',
    'Sem nome': 'No name',
    'Sim': 'Yes',
    'Sou Idoso': 'I am a senior',
    'Sou Responsavel': 'I am a caregiver',
    'Tomei': 'Taken',
    'Título': 'Title',
    'Tudo certo': 'All set',
    'Tente de novo.': 'Try again.',
    'Esta e a tela inicial onde aparecera as proximas tarefas': 'This is the home screen where upcoming tasks will appear',
    'Acima esta suas informacoes, para ver e analisa-las, clique no seu icone de perfil': 'Your information is above. To view it, tap your profile icon',
    'Abaixo esta a barra de navegacao, onde voce pode alterar entre as abas: Home e Configuracoes': 'The navigation bar is below, where you can switch between Home and Settings',
    'Toque em um idoso para abrir os cuidados': 'Tap a senior to open care details',
    'Uso contínuo?': 'Continuous use?',
    'Use pelo menos 6 caracteres.': 'Use at least 6 characters.',
    'Voltar': 'Back',
    'continuar usando nosso app': 'continue using our app',
    'informações': 'information',
    'Avancar': 'Next',
    'Aqui voce altera sua foto.': 'Here you can change your photo.',
    'ou': 'or',
    language: 'Language',
    languageDescription: 'Choose the app language.',
    languageTitle: 'Select language',
    logout: 'Sign out',
    logoutQuestion: 'Do you want to sign out?',
    logoutText: 'You will return to the start.',
    notifications: 'Notifications',
    panel: 'Panel',
    responsible: 'Caregiver',
    senior: 'Senior',
    settings: 'SETTINGS',
  },
  es: {
    about: 'Acerca de',
    'Abra o e-mail e toque no link.': 'Abre el correo y toca el enlace.',
    'Ainda não': 'Todavía no',
    'adicionado.': 'agregado.',
    'Aplicativo de apoio ao cuidado do idoso': 'Aplicación de apoyo al cuidado del adulto mayor',
    'Anotacao': 'Nota',
    'Anotação': 'Nota',
    'Anotacoes': 'Notas',
    'Anotações do idoso': 'Notas del adulto mayor',
    'As medicações são cadastradas pelo responsável. Confirme quando tomar.': 'Los medicamentos son registrados por el responsable. Confirma cuando los tomes.',
    'As senhas nao sao iguais.': 'Las contraseñas no coinciden.',
    'BackEnd': 'BackEnd',
    'Banco de Dados': 'Base de datos',
    'Bem Vindo ao Amaidoso': 'Bienvenido a Amaidoso',
    'Bem vindo ao Amaidoso': 'Bienvenido a Amaidoso',
    'Cadastrar idoso': 'Registrar adulto mayor',
    'Cadastrar medicação': 'Registrar medicación',
    'CADASTRAR MEDICAÇÃO': 'REGISTRAR MEDICACIÓN',
    'Campos obrigatórios': 'Campos obligatorios',
    cancel: 'Cancelar',
    'Cancelar': 'Cancelar',
    'Confirme o novo e-mail': 'Confirma el nuevo correo',
    'Confirme seu e-mail': 'Confirma tu correo',
    'Confirmada': 'Confirmada',
    'Confirmar Medicacoes': 'Confirmar medicaciones',
    'Confirmar Alteração': 'Confirmar cambio',
    'Confirmar alterações': 'Confirmar cambios',
    'Confirmar senha': 'Confirmar contraseña',
    'Continuar': 'Continuar',
    configuration: 'Configuración',
    'Configurações': 'Configuración',
    'Criando...': 'Creando...',
    'Criar Conta': 'Crear cuenta',
    'Criar lembrete': 'Crear recordatorio',
    'Cria uma agora': 'Crea una ahora',
    'Crie Agora': 'Crear cuenta',
    'Crie uma senha para o novo acesso': 'Crea una contraseña para el nuevo acceso',
    'CPF e senha definem o login e não são alterados por aqui.': 'CPF y contraseña definen el inicio de sesión y no se cambian aquí.',
    'CPF inválido': 'CPF inválido',
    'Cuidados do idoso': 'Cuidados del adulto mayor',
    'Data': 'Fecha',
    'Data de Nascimento': 'Fecha de nacimiento',
    'Data de nascimento': 'Fecha de nacimiento',
    'Definir': 'Definir',
    'Definir Data e Hora': 'Definir fecha y hora',
    'Descrição': 'Descripción',
    'Documentação': 'Documentación',
    'Digite um e-mail valido.': 'Ingresa un correo válido.',
    'Digite um email valido.': 'Ingresa un correo válido.',
    'Digite uma data valida.': 'Ingresa una fecha válida.',
    'Digite sua senha atual': 'Ingresa tu contraseña actual',
    'Digite os 11 numeros do CPF.': 'Ingresa los 11 números del CPF.',
    'Depois': 'Después',
    'Dose do medicamento': 'Dosis del medicamento',
    'Demorou demais': 'Está tardando demasiado',
    editProfile: 'Editar perfil',
    'Editar': 'Editar',
    'Editar foto': 'Editar foto',
    'Editar idoso': 'Editar adulto mayor',
    'Editar Perfil': 'Editar perfil',
    email: 'Correo',
    'Email': 'Correo',
    'E-mail de acesso': 'Correo de acceso',
    'Email inválido': 'Correo inválido',
    'Em breve': 'Pronto',
    'Entendi': 'Entendido',
    'Enviamos um link para': 'Enviamos un enlace a',
    'Entrando...': 'Entrando...',
    'Entrar': 'Entrar',
    'Entre Agora': 'Entrar',
    'Entre agora': 'Entrar ahora',
    'Erro': 'Error',
    'Erro no cadastro': 'Error de registro',
    'Erro no login': 'Error de inicio',
    'Escolher foto': 'Elegir foto',
    'Escolha a frequencia.': 'Elige la frecuencia.',
    'Escreva algo primeiro.': 'Escribe algo primero.',
    'Escreva aqui...': 'Escribe aquí...',
    'FrontEnd': 'FrontEnd',
    'FrontEnd e BackEnd': 'FrontEnd y BackEnd',
    'Frequência': 'Frecuencia',
    'Frequência obrigatória': 'Frecuencia obligatoria',
    'Fechar': 'Cerrar',
    help: 'Ayuda',
    home: 'Inicio',
    'Home': 'Inicio',
    'Idioma': 'Idioma',
    'Idoso cadastrado.': 'Adulto mayor registrado.',
    'Idoso não encontrado': 'Adulto mayor no encontrado',
    'Idosos cadastrados': 'Adultos mayores registrados',
    'Ir para login': 'Ir al inicio de sesión',
    'Ir agora': 'Ir ahora',
    'Lembretes': 'Recordatorios',
    'Limpar': 'Limpiar',
    'Login feito': 'Inicio correcto',
    'Marcar como visto': 'Marcar como visto',
    'Medicações': 'Medicaciones',
    'Medicações e confirmações': 'Medicaciones y confirmaciones',
    'Membros e contribuidores': 'Miembros y contribuidores',
    'Minhas anotações': 'Mis notas',
    'Nascimento': 'Nacimiento',
    'Nenhum Idoso cadastrado!': '¡Ningún adulto mayor registrado!',
    'Nenhum lembrete por enquanto.': 'No hay recordatorios por ahora.',
    'Nenhuma anotação ainda.': 'Aún no hay notas.',
    'Nenhuma anotação feita pelo idoso.': 'No hay notas del adulto mayor.',
    'Nenhuma medicação cadastrada.': 'No hay medicación registrada.',
    'Nome': 'Nombre',
    'Nome Completo': 'Nombre completo',
    'Nome completo': 'Nombre completo',
    'Nome de Usuário': 'Nombre de usuario',
    'Novo': 'Nuevo',
    'Novo remedio': 'Nueva medicación',
    'Novo link enviado.': 'Nuevo enlace enviado.',
    'Nova anotação': 'Nueva nota',
    'Nova senha (min. 6 caracteres)': 'Nueva contraseña (mín. 6 caracteres)',
    'Não': 'No',
    'Nao, obrigado': 'No, gracias',
    'Não possui uma conta?': '¿No tienes una cuenta?',
    'Ok': 'OK',
    'Ola': 'Hola',
    'Olá': 'Hola',
    'O idoso vai entrar com CPF e senha.': 'El adulto mayor entrará con CPF y contraseña.',
    'O idoso vai entrar no app usando este CPF e senha.': 'El adulto mayor entrará en la app usando este CPF y contraseña.',
    'Os lembretes são criados pelo seu responsável.': 'Los recordatorios los crea tu responsable.',
    'Parece que essa e a sua primeira vez aqui, deseja realizar o tutorial?': 'Parece que es tu primera vez aquí. ¿Deseas hacer el tutorial?',
    'Pendente': 'Pendiente',
    'Perfil atualizado.': 'Perfil actualizado.',
    'Pode continuar.': 'Puedes continuar.',
    'Possui uma conta?': '¿Ya tienes una cuenta?',
    'Por favor entre na sua conta para': 'Por favor entra en tu cuenta para',
    'Preencha os campos com suas': 'Completa los campos con tu',
    'Preencha CPF e senha.': 'Completa CPF y contraseña.',
    'Preencha e-mail e senha.': 'Completa correo y contraseña.',
    'Preencha medicamento e dose.': 'Completa medicación y dosis.',
    'Preencha titulo e horario.': 'Completa título y horario.',
    'Preencha todos os campos.': 'Completa todos los campos.',
    'Permissão necessária': 'Permiso necesario',
    'Permita acessar suas fotos.': 'Permite acceder a tus fotos.',
    'Projeto de TCC': 'Proyecto de TCC',
    'Recuperar senha': 'Recuperar contraseña',
    'Reenviar link': 'Reenviar enlace',
    'Reenviar link em': 'Reenviar enlace en',
    'Reenviando...': 'Reenviando...',
    'remedios adicionados.': 'medicaciones agregadas.',
    'Remover foto': 'Eliminar foto',
    'Salvar': 'Guardar',
    'Salvar anotação': 'Guardar nota',
    'Salvar lembrete': 'Guardar recordatorio',
    'Salvando...': 'Guardando...',
    'Selecione um idoso.': 'Selecciona un adulto mayor.',
    'Senha': 'Contraseña',
    'Senha (mín. 6 caracteres)': 'Contraseña (mín. 6 caracteres)',
    'Senha atual para alterar e-mail': 'Contraseña actual para cambiar correo',
    'Sem nome': 'Sin nombre',
    'Sim': 'Sí',
    'Sou Idoso': 'Soy adulto mayor',
    'Sou Responsavel': 'Soy responsable',
    'Tomei': 'Tomé',
    'Título': 'Título',
    'Tudo certo': 'Todo listo',
    'Tente de novo.': 'Inténtalo de nuevo.',
    'Esta e a tela inicial onde aparecera as proximas tarefas': 'Esta es la pantalla inicial donde aparecerán las próximas tareas',
    'Acima esta suas informacoes, para ver e analisa-las, clique no seu icone de perfil': 'Arriba está tu información. Para verla, toca tu ícono de perfil',
    'Abaixo esta a barra de navegacao, onde voce pode alterar entre as abas: Home e Configuracoes': 'Abajo está la barra de navegación, donde puedes alternar entre Inicio y Configuración',
    'Toque em um idoso para abrir os cuidados': 'Toca un adulto mayor para abrir los cuidados',
    'Uso contínuo?': '¿Uso continuo?',
    'Use pelo menos 6 caracteres.': 'Usa al menos 6 caracteres.',
    'Voltar': 'Volver',
    'continuar usando nosso app': 'seguir usando nuestra app',
    'informações': 'información',
    'Avancar': 'Avanzar',
    'Aqui voce altera sua foto.': 'Aquí puedes cambiar tu foto.',
    'ou': 'o',
    language: 'Idioma',
    languageDescription: 'Elige el idioma de la aplicación.',
    languageTitle: 'Seleccionar idioma',
    logout: 'Salir',
    logoutQuestion: '¿Deseas cerrar sesión?',
    logoutText: 'Volverás al inicio.',
    notifications: 'Notificaciones',
    panel: 'Panel',
    responsible: 'Responsable',
    senior: 'Adulto mayor',
    settings: 'AJUSTES',
  },
};

const LanguageContext = React.createContext<LanguageContextValue | undefined>(undefined);

function isAppLanguage(value: string | null): value is AppLanguage {
  return value === 'pt' || value === 'en' || value === 'es';
}

function getDeviceLanguage(): AppLanguage {
  const locale =
    Platform.OS === 'ios'
      ? NativeModules.SettingsManager?.settings?.AppleLocale ??
        NativeModules.SettingsManager?.settings?.AppleLanguages?.[0]
      : Platform.OS === 'android'
        ? NativeModules.I18nManager?.localeIdentifier
        : globalThis.navigator?.language;

  const languageCode = String(locale ?? '').split(/[-_]/)[0].toLowerCase();

  if (isAppLanguage(languageCode)) {
    return languageCode;
  }

  return 'pt';
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = React.useState<AppLanguage>(() => getDeviceLanguage());

  React.useEffect(() => {
    void AsyncStorage.getItem(LANGUAGE_STORAGE_KEY)
      .then((storedLanguage) => {
        if (isAppLanguage(storedLanguage)) {
          setLanguageState(storedLanguage);
          return;
        }

        setLanguageState(getDeviceLanguage());
      })
      .catch(() => undefined);
  }, []);

  const setLanguage = React.useCallback(async (nextLanguage: AppLanguage) => {
    setLanguageState(nextLanguage);
    await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage);
  }, []);

  const t = React.useCallback(
    (key: string) => translations[language][key] ?? translations.pt[key] ?? key,
    [language],
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = React.useContext(LanguageContext);

  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }

  return context;
}
